name: example-environment
channels:
  - psi4/label/dev
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - rdkit
  - psi4
  - dftd3
  - ipywidgets
  - widgetsnbextension
  - scikit-image
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - pythreejs
    - fortecubeview
    
